name: CI Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint:
    name: Run Lint-Staged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Lint-Staged
        run: npx lint-staged

  jest:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Check for Jest Test Files
        id: check-jest
        run: |
          if [ -z "$(find ./src -type f -name '*.test.*')" ]; then
            echo "No Jest test files found. Skipping Jest tests and build."
            echo "::set-output name=skip::true"
            exit 0
          else
            echo "Jest test files found. Proceeding with build."
          fi

      - name: Build Application
        if: steps.check-jest.outputs.skip != 'true'
        run: npm run build --verbose

      - name: Run Jest
        if: steps.check-jest.outputs.skip != 'true'
        run: npm test --verbose

  cypress:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Check for Cypress Test Files
        id: check-cypress
        run: |
          if [ -z "$(find ./cypress/e2e -type f -name '*.cy.*')" ]; then
            echo "No Cypress test files found. Skipping Cypress tests and build."
            echo "::set-output name=skip::true"
            exit 0
          else
            echo "Cypress test files found. Proceeding with build."
          fi

      - name: Build Application
        if: steps.check-cypress.outputs.skip != 'true'
        run: npm run build --verbose

      - name: Start Development Server
        if: steps.check-cypress.outputs.skip != 'true'
        run: nohup npm run dev > nohup.out 2>&1 &
        env:
          NODE_ENV: development

      - name: Debug Server Logs
        if: steps.check-cypress.outputs.skip != 'true'
        run: cat nohup.out || echo "No server logs found."

      - name: Check Running Processes
        if: steps.check-cypress.outputs.skip != 'true'
        run: ps aux | grep node

      - name: Wait for server to start
        if: steps.check-cypress.outputs.skip != 'true'
        run: npx wait-on http://localhost:3000 --timeout 120000 --verbose

      - name: Run Cypress
        if: steps.check-cypress.outputs.skip != 'true'
        run: npm run cypress:run

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier Check
        run: npx prettier --check .
