name: CI Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint:
    name: Run Lint-Staged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Lint-Staged
        run: npx lint-staged

  jest:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Check and Run Jest Tests
        run: |
          if [ -z "$(find ./src -type f -name '*.test.*')" ]; then
            echo "No Jest test files found. Skipping Jest tests.";
          else
            echo "Jest test files found. Running tests.";
            npm test --verbose;
          fi

  cypress:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') || 'default' }}
          restore-keys: |
            ${{ runner.os }}-node-


      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        run: echo "NEXT_PUBLIC_API_URL=https://api.example.com" >> .env.local

      - name: Build Application
        run: npm run build --verbose

      - name: Start Development Server
        run: nohup npm run dev > nohup.out 2>&1 &
        env:
          NODE_ENV: development

      - name: Debug Server Logs
        run: cat nohup.out || echo "No server logs found."

      - name: Check Running Processes
        run: ps aux | grep node

      - name: Wait for server to start
        run: npx wait-on http://localhost:3000 --timeout 120000 --verbose

      - name: Check and Run Cypress Tests
        run: |
          if [ -z "$(find ./cypress/e2e -type f -name '*.cy.*')" ]; then
            echo "No Cypress test files found. Skipping Cypress tests.";
          else
            echo "Cypress test files found. Running tests.";
            npm run cypress:run;
          fi

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier Check
        run: npx prettier --check .
        
